# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# A minimal left prompt
format = """
$directory\
\n$character
"""

# move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = 'ğŸ’»' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
symbol = 'î˜§ '